export default {
  SET_EDITING: 'SET_EDITING',
  SET_SELECTED_SUGGESTION: 'SET_SELECTED_SUGGESTION',
  REMOVE_SELECTED_SUGGESTION: 'REMOVE_SELECTED_SUGGESTION',
  CHANGE_SELECTED_SUGGESTION: 'CHANGE_SELECTED_SUGGESTION',
  CLEAR_SELECTED_SUGGESTION: 'CLEAR_SELECTED_SUGGESTION',
};
