<template>
  <div>
    <bh-icon
      value="botinho"
      size="normal"/>
    <bh-icon
      value="account"
      size="normal"/>
    <bh-icon
      value="check"
      size="normal"/>
    <bh-icon
      value="chevron-right"
      size="normal"/>
    <bh-icon
      value="close-circle"
      size="normal"/>
    <bh-icon
      value="close"
      size="normal"/>
    <bh-icon
      value="code-tags"
      size="normal"/>
    <bh-icon
      value="help-text"
      size="normal"/>
    <bh-icon
      value="dots-horizontal"
      size="normal"/>
    <bh-icon
      value="dots-vertical"
      size="normal"/>
    <bh-icon
      value="earth"
      size="normal"/>
    <bh-icon
      value="equal"
      size="normal"/>
    <bh-icon
      value="exclamation"
      size="normal"/>
    <bh-icon
      value="flag-variant"
      size="normal"/>
    <bh-icon
      value="home"
      size="normal"/>
    <bh-icon
      value="magnify"
      size="normal"/>
    <bh-icon
      value="menu-down"
      size="normal"/>
    <bh-icon
      value="minus"
      size="ormal"/>
    <bh-icon
      value="plus-circle"
      size="normal"/>
    <bh-icon
      value="refresh"
      size="normal"/>
    <bh-icon
      value="school"
      size="normal"/>
    <bh-icon
      value="alert"
      size="normal"/>
    <bh-icon
      value="clipboard-alert"
      size="normal"/>
    <bh-icon
      value="clipboard-text-outline"
      size="normal"/>
    <bh-icon
      value="account-edit"
      size="normal"/>
    <bh-icon
      value="lock-reset"
      size="normal"/>
    <bh-icon
      value="warning"
      size="normal"/>
    <bh-icon
      value="sentence"
      size="normal"/>
    <bh-icon
      value="language"
      size="normal"/>
    <bh-icon
      value="question"
      size="normal"/>
    <bh-icon
      value="business"
      size="normal"/>
    <bh-icon
      value="commercial"
      size="normal"/>
    <bh-icon
      value="culture"
      size="normal"/>
    <bh-icon
      value="customer-service"
      size="normal"/>
    <bh-icon
      value="education"
      size="normal"/>
    <bh-icon
      value="finances"
      size="normal"/>
    <bh-icon
      value="food"
      size="normal"/>
    <bh-icon
      value="health"
      size="normal"/>
    <bh-icon
      value="social"
      size="normal"/>
    <bh-icon
      value="tech"
      size="normal"/>
    <bh-icon
      value="config"
      size="normal"/>
  </div>
</template>

<script>
export default {
  name: 'IconExamples',
};
</script>
