<template>
  <div>
    <div class="bh-grid bh-grid--multiline">
      <bh-icon
        class="bh-grid__item"
        value="botinho"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="account"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="check"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="chevron-right"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="close-circle"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="close"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="code-tags"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="help-text"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="dots-horizontal"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="dots-vertical"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="earth"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="equal"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="exclamation"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="flag-br"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="flag-de"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="flag-es"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="flag-fr"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="flag-id"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="flag-it"
        size="normal"/>
    </div>
    <div class="bh-grid bh-grid--multiline">
      <bh-icon
        class="bh-grid__item"
        value="flag-mn"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="flag-nl"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="flag-pt"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="flag-us"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="flag-variant"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="home"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="magnify"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="menu-down"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="minus"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="plus-circle"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="refresh"
        size="normal"/>
      <bh-icon
        class="bh-grid__item"
        value="school"
        size="normal"/>
    </div>
  </div>
</template>

<script>
export default {
  name: 'IconExamples',
};
</script>
