name: Build Bothub WebApp (Push Tag)

on:
  push:
    tags:
      - '*.*.*-develop'
      - '*.*.*-staging'
      - '*.*.*'

jobs:
  call-workflow:
    uses: weni-ai/actions-workflows/.github/workflows/reusable-workflow.yaml@main
    with:
      docker_image: irdgss/sandbox
      target_repository: weni-ai/kubernetes-manifests-artificial-intelligence
      target_repository_branch: sandbox
      target_application: webapp
      target_patch_file: deployment-webapp.json
        #secrets: inherit #WORKS ONLY IN SAME ORG
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      DEVOPS_GITHUB_PERMANENT_TOKEN: ${{ secrets.DEVOPS_GITHUB_PERMANENT_TOKEN }}
